### ISSUE TITLE
integrating qgis into expressJs based web application for tiff images

### ISSUE THREAD

**Issue by Rjaat** [qgis/qgis-js#28]
I am working on an expressJS based web application which is primarily intended to object detection from tiff images. As of now, i am using openseadragon for loading the tiff images inside the application but it takes too much time. So i had a thought of using QGIS interface inside my application for loading the tiff images.
can anyone help with this?

**Comment by boardend** [comment]
Hi @Rjaat 
As for now, qgis-js faces an architectural issue which prevents loading a project with remote/COG tiff images (tracked in https://github.com/qgis/qgis-js/issues/4). This means that for the moment you would have to fetch the entire image and upload it to the qgis-js runtime in order to render it. This works fine, for example in the [village](https://github.com/qgis/qgis-js/tree/main/sites/dev/public/projects/village) project, but is probably not feasible for a large tiff image.
Note that if you can export it as a COG, you could also use OpenLayers directly (see https://openlayers.org/en/latest/examples/cog.html)

**Comment by boardend** [comment]
@Rjaat can this be closed?

**Comment by boardend** [comment]
Closed because of missing feedback
