### ISSUE TITLE
Labels not rendered correctly in XYZ Tiles demo

### ISSUE THREAD

**Issue by max-mapper** [qgis/qgis-js#43]
Using this project: [eaton-vegetation-map.tar.gz](https://github.com/user-attachments/files/15917444/eaton-vegetation-map.tar.gz)

The labels are getting cut off along certain vertical lines, maybe a tiling issue

![Screenshot_20240307](https://github.com/qgis/qgis-js/assets/39759/d06805eb-40a5-434b-8d57-b1fd367d5e67)

**Comment by boardend** [comment]
Try to set an `extentBufferFactor` for your [`QgisXYZDataSource`](https://github.com/qgis/qgis-js/blob/main/packages/qgis-js-ol/src/QgisXYZDataSource.ts); `0.5` should be a good starting point..?

And if you are after a perfect image, use a `QgisCanvasDataSource` instead of a `QgisXYZDataSource`

Hope this helps?

**Comment by max-mapper** [comment]
Thanks, looks like extentBufferFactor of 4 is working well for me. I tried
0.5, 1, 2, and 3, and they all resulted in the above rendering artifacts as
I zoomed in.
