### ISSUE TITLE
Opacity change latency

### ISSUE THREAD

**Issue by max-mapper** [qgis/qgis-js#44]
Hello, I have been tinkering with the repo and was seeing how it can do with layered historical imagery for comparing effects of flooding https://max-mapper.github.io/journal/maps/?repo=max-mapper/journal/mapdata/ec-floods

One issue is an adjustment to a single layer opacity e.g.

```js
layer.opacity = 50 // WebGLTileLayer
source.clear(); // QgisXYZDataSource
layer.getRenderer().clearCache(); 
layer.changed();
```

... causes a full re-render which can take many seconds, especially on Android. I was just curious if there is a way to cache or avoid the rerender and make opacity adjustments feel instant. Thank you for any advice!

**Comment by boardend** [comment]
Are you using any QGIS raster analysis/styling/re-projections, so that you need qgis-js for this map? You might get away with just plain OpenLayers, where you can change the opacity for the composition of the layers. So there will be no need for a reload.

If you want to do this with qgis-js, the [`QgsMapRendererCache`](https://api.qgis.org/api/classQgsMapRendererCache.html) should help in this scenario. But you would have to compile qgis-js and add this to the [QgisApi.](https://github.com/qgis/qgis-js/blob/main/src/api/QgisApi.cpp) by yourself, as it is not used at the moment.

**Comment by max-mapper** [comment]
Makes sense, thanks!
